name: Deploy to Server via SFTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Checkout and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload Files
        uses: pontago/lftp-deploy-action@v1.0.1
        with:
          protocol: ftp  # или ftp, ftps
          host: ${{ secrets.SFTP_HOST }} # замените на ваш хост
          username: ${{ secrets.SFTP_USERNAME }}  # логин для доступа
          password: ${{ secrets.SFTP_PASSWORD }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}  # если используете SSH-ключ
          local_dir: ./local/  # локальная директория для загрузки
          remote_dir: /  # удалённая директория
          
env:
  LFTP_DEBUG: "3"  # уровень детализации логов lftp
